### ISSUE TITLE
Better position information

### ISSUE THREAD

**Issue by laughedelic** [mschuchard/linter-travis-lint#1]
Right now all errors are reposted with position 1:1.  As I see from the `travis lint` output, it gives you information about the location in terms of the YAML structure. So I guess with some simple YAML parsing this could be translated to a line:column position for the linter..

**Comment by mschuchard** [comment]
I don't see this kind of information in 1.8.8. Could you show an example?

**Comment by laughedelic** [comment]
Here's an example config:

```yaml
sudo: false
language: scala
jdk: oraclejdk8
scala: 2.12.3
script: sbt test
notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/foo
    on_start: false           # <-- problem here
cache:
  directorie:                 # <-- problem here
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
```

And here is the linter's output:

```
>  travis lint --no-interactive .travis.yml
Warnings for .travis.yml:
[x] in notifications.webhooks section: dropping on_start section: illegal value false
[x] value for cache section is empty, dropping
[x] in cache section: unexpected key directorie, dropping
```

As you every warning has some clue about location: 
- in `notifications.webhooks` section, `on_start` section
- value for `cache` section
- in `cache` section
